/**
 * Every process flow from "PROCESS FLOWS FOR TRT.xlsx", stage for stage.
 * Generated from the workbook — edit the workbook and re-extract rather than
 * hand-editing, so the app and the source document stay in step.
 */

export type FlowStageSeed = {
  seq: number;
  name: string;
  actionBy: string | null;
  steps: string | null;
  documents: string | null;
  decisionMaker: string | null;
  criteria: string | null;
  stakeholders: string | null;
  duration: string | null;
};

export type FlowSeed = {
  code: string;
  name: string;
  category: string;
  summary: string;
  appRoute: string | null;
  sourceSheet: string;
  stages: FlowStageSeed[];
};

export const FLOWS: FlowSeed[] = [
  {
    code: "MATVIS",
    name: "Materials Visibility & Usage",
    category: "Inventory",
    summary: "Register a material, publish it to the catalogue, check availability across the group before buying outside it.",
    appRoute: "/products",
    sourceSheet: "Materials Visibility and Usage",
    stages: [
      { seq: 1, name: "Material / Accessory Identification", actionBy: "Supply Chain / Nobox", steps: "Identify materials and accessories that need to be visible in the system.", documents: "Supplier documents; GRN; stock records; photographs; material specifications", decisionMaker: "Operations", criteria: "Material is identifiable and ownership/location can be confirmed.", stakeholders: "Operations, Procurement, Nobox, Warehouse", duration: null },
      { seq: 2, name: "Material Registration", actionBy: "Operations", steps: "Create and validate the material record in the central system.", documents: "Material Register; Material Code; Photo; Specification Form", decisionMaker: "Operations", criteria: "Name, category, code, owner, location, unit and quantity are complete and verified.", stakeholders: "Operations, Warehouse, Procurement, Nobox", duration: null },
      { seq: 3, name: "Catalogue Publication", actionBy: "Operations", steps: "Make approved materials and accessories visible to authorised users.", documents: "Central Material Catalogue; Inventory Database", decisionMaker: "Operations", criteria: "Material record is complete, accurate and approved.", stakeholders: "Design, Architects, Procurement, Production, Sales", duration: null },
      { seq: 4, name: "Design Material Check", actionBy: "Design / Architects", steps: "Search the central catalogue before specifying or designing with any materials.", documents: "Material Catalogue; Search/Filter; Design Brief", decisionMaker: "Design Lead", criteria: "Existing material meets aesthetic, technical and quantity requirements.", stakeholders: "Design, Operations, Procurement, Production", duration: null },
      { seq: 5, name: "Internal Material Selection", actionBy: "Design / Production / Procurement", steps: "Select an available material or accessory for the project/request.", documents: "Material Request Form; Material Catalogue", decisionMaker: "Relevant Department Lead", criteria: "Material is available and suitable for the intended application.", stakeholders: "Design, Production, Operations, Nobox", duration: null },
      { seq: 6, name: "Material Reservation", actionBy: "Operations", steps: "Reserve selected materials against a project, client or production order.", documents: "Reservation Module; Project/Job Number; Reservation Log", decisionMaker: "Operations", criteria: "Sufficient unreserved quantity is available.", stakeholders: "Operations, Design, Production, Warehouse", duration: null },
      { seq: 7, name: "Material Availability Check", actionBy: "Procurement", steps: "Check internal and sister-company stock before raising an external procurement request.", documents: "Procurement Request; Central Inventory; Availability Report", decisionMaker: "Procurement Lead", criteria: "No suitable material is available internally, or available stock is insufficient/unsuitable.", stakeholders: "1.0", duration: null },
      { seq: 8, name: "Inter-company Material Request", actionBy: "Requesting Department / Operations", steps: "Request transfer or purchase of materials/accessories from a Nobox where applicable.", documents: "Inter-company Request; Transfer Note; Approval Record", decisionMaker: "Operations / Management", criteria: "Material is available from Nobox and transfer is appropriate.", stakeholders: "Operations, Nobox, Requesting Department, Finance", duration: null },
      { seq: 9, name: "External Procurement", actionBy: "Procurement", steps: "Procure materials not available within the group.", documents: "Purchase Requisition; RFQ; Purchase Order; Supplier Documents", decisionMaker: "Procurement / Management", criteria: "Internal availability check completed and requirement approved.", stakeholders: "Procurement, Operations, Finance, Supplier", duration: null },
      { seq: 10, name: "Material Receipt & Verification", actionBy: "Warehouse / Operations", steps: "Receive, inspect and confirm quantity/specification of newly procured or transferred materials.", documents: "GRN; Delivery Note; Inspection Checklist; Photos", decisionMaker: "Operations / Warehouse", criteria: "Received material matches approved request/order and is fit for use.", stakeholders: "Operations, Warehouse, Procurement, Finance", duration: null },
      { seq: 11, name: "Stock Update", actionBy: "Operations / Warehouse", steps: "Update available, reserved and issued quantities in the central system.", documents: "Inventory System; Stock Movement Log", decisionMaker: "Operations", criteria: "Physical stock reconciles with system records.", stakeholders: "Operations, Warehouse, Design, Procurement, Production", duration: null },
      { seq: 12, name: "Material Issue / Allocation", actionBy: "Warehouse / Operations", steps: "Issue approved materials to production, design or project teams.", documents: "Material Issue Note; Reservation Record; Job Card", decisionMaker: "Operations / Warehouse", criteria: "Request is approved and material is reserved/available.", stakeholders: "Operations, Warehouse, Production, Design", duration: null },
      { seq: 13, name: "Production / Project Use", actionBy: "Production / Project Team", steps: "Use allocated materials for the approved project or production requirement.", documents: "Production Order; Job Card; Bill of Materials", decisionMaker: "Production Lead / Project Lead", criteria: "Correct material and quantity are used against the approved requirement.", stakeholders: "Production, Design, Operations", duration: null },
      { seq: 14, name: "Stock Reconciliation", actionBy: "Operations", steps: "Reconcile system quantities against physical stock and investigate variances.", documents: "Stock Reconciliation Report; Cycle Count Sheet; Variance Log", decisionMaker: "Operations Manager", criteria: "Physical and system stock are reconciled or variances documented.", stakeholders: "Operations, Warehouse, Finance, Procurement", duration: null },
      { seq: 15, name: "Utilisation & Ageing Review", actionBy: "Operations", steps: "Review slow-moving, unused and sister-company materials and identify utilisation opportunities.", documents: "Operations Dashboard; Ageing Report; Utilisation Report", decisionMaker: "Operations Manager", criteria: "Materials meet agreed ageing/slow-moving thresholds.", stakeholders: "Operations, Design, Sales, Nobox, Management", duration: null },
      { seq: 16, name: "Continuous Improvement / Reporting", actionBy: "Operations", steps: "Report utilisation, procurement avoidance, stock ageing and internal material usage and recommend actions.", documents: "Management Dashboard; KPI Report; Action Tracker", decisionMaker: "Management", criteria: "KPI trends and issues have been reviewed and actions assigned.", stakeholders: "Operations, Design, Procurement, Production, Sales, Nobox, Management", duration: null },
    ],
  },
  {
    code: "STORE",
    name: "Store Issuance & Reconciliation",
    category: "Inventory",
    summary: "BOQ through MRP and MIV to store issuance, site receipt, returns and reconciliation.",
    appRoute: "/requisitions",
    sourceSheet: "STORE",
    stages: [
      { seq: 1, name: "Project file Submission and Receipt", actionBy: "Office", steps: "BOQ submission to factory", documents: "Project file, Email log", decisionMaker: "CPO", criteria: "Completeness, accuracy", stakeholders: "Office, CPO", duration: "0.25" },
      { seq: 2, name: "BOQ Validation", actionBy: "CPO", steps: "Verify BOQ", documents: "BOQ Register (Excel)", decisionMaker: "CPO", criteria: "Valid scope, no duplication", stakeholders: "Factory Admin/", duration: "0.25" },
      { seq: 3, name: "Material Planning (Optimization)", actionBy: "Operations Planner", steps: "Create MRP (material requirement plan through optimization)", documents: "MRP Sheet, Standard consumption guide", decisionMaker: "Factory Manager", criteria: "Efficiency, accuracy vs BOQ", stakeholders: "CPO, FM", duration: "1.0" },
      { seq: 4, name: "MRP Review", actionBy: "Factory Manager", steps: "Approve or reject MRP", documents: "Approval Sheet, Sign-off log", decisionMaker: "Factory Manager", criteria: "Cost, feasibility, job timeline", stakeholders: "Ops, Store", duration: "1.0" },
      { seq: 5, name: "MIV Creation", actionBy: "Factory Manager", steps: "Convert approved MRP to MIV", documents: "Material Issue Voucher (MIV) Form", decisionMaker: "Factory Manager", criteria: "Approved MRP only", stakeholders: "Store, Control", duration: "0.25" },
      { seq: 6, name: "Store Issuance", actionBy: "Storekeeper", steps: "Issue materials physically", documents: "MIV + Issue Log Sheet", decisionMaker: "Factory Manager", criteria: "Match MIV exactly", stakeholders: "Factory PS, FM", duration: "0.25" },
      { seq: 7, name: "Site Receipt", actionBy: "Project Supervisor", steps: "Receive materials on site", documents: "Site Receipt Form", decisionMaker: "Site Supervisor", criteria: "Quantity match", stakeholders: "Store, Ops", duration: "0.5" },
      { seq: 8, name: "Site Usage Tracking", actionBy: "Project Supervisor", steps: "Daily usage tracking", documents: "Daily Usage Log Sheet", decisionMaker: "Site Supervisor", criteria: "Usage consistency", stakeholders: "FM, Control", duration: "Daily" },
      { seq: 9, name: "Returns Processing", actionBy: "Project Supervisor + Storekeeper", steps: "Return unused materials", documents: "Return Note Form", decisionMaker: "Storekeeper", criteria: "Full reconciliation", stakeholders: "FM/Project Supervisor", duration: "1.0" },
      { seq: 10, name: "Weekly Reconciliation", actionBy: "Factory Manager", steps: "Compare issue vs usage", documents: "Variance Report Template", decisionMaker: "Factory Manager", criteria: "Variance threshold \u22645%", stakeholders: "Store/Factory Manager/Operations", duration: "Weekly" },
      { seq: 11, name: "Monthly Audit", actionBy: "Factory Manager", steps: "Full inventory audit", documents: "Audit Report Sheet", decisionMaker: "Management", criteria: "Accuracy, loss detection", stakeholders: "Entire management team/Operations/Storekeeper", duration: "1.0" },
    ],
  },
  {
    code: "MATREC",
    name: "Material Reception",
    category: "Inventory",
    summary: "Receive a delivery, verify quantity and condition, shelve it and issue to end users.",
    appRoute: "/receipts",
    sourceSheet: "MATERIAL RECEPTION PROCESS",
    stages: [
      { seq: 1, name: "Material Collection & Receipt", actionBy: "Store Officer / Inventory Officer", steps: "Receive requested materials from:\nProcurement Assistant (vendor-arranged supplies)\nExternal vendors and delivery personnel\nVerify delivery note against purchase order or approved request\nAcknowledge receipt from delivery personnel", documents: "Purchase Order (PO)\nDelivery Note\nMaterial Receipt Register", decisionMaker: null, criteria: null, stakeholders: "Procurement Assistant\nVendors\nDelivery Personnel", duration: "0.5" },
      { seq: 2, name: "Material Verification & Confirmation", actionBy: "Store Officer / Inventory Officer", steps: "Physically inspect materials for:\nQuantity\nType\nColour\nQuality and damage\nConfirm materials in the system (ERP / Excel / Stock Register)\nFlag discrepancies and report immediately to Procurement", documents: "Material Inspection Checklist\nInventory Management System / Stock Card\nDiscrepancy Report Template", decisionMaker: null, criteria: null, stakeholders: "Procurement Assistant", duration: "0.5" },
      { seq: 3, name: "Shelving & Storage", actionBy: "Store Officer", steps: "Classify materials (boards, edge tapes, accessories, consumables)\nAssign materials to designated shelf columns\nLabel shelves clearly with material description and codes\nUpdate shelf location in inventory records", documents: "Shelf Location Map\nInventory Ledger\nMaterial Labels", decisionMaker: null, criteria: null, stakeholders: "Inventory Control\nFactory Operations", duration: "0.5" },
      { seq: 4, name: "Material Issuance to End Users", actionBy: "Store Officer", steps: "Receive approved material requisition form from:\nFactory Operations\nCutting Section\nUpholstery\nOther Production Units\nCross-check requisition against available stock\nIssue materials accordingly\nUpdate inventory balance immediately", documents: "Material Requisition Form\nStock Issue Voucher\nInventory System", decisionMaker: null, criteria: null, stakeholders: "End Users (Production Sections)\nFactory Operations\nCompliance Manager", duration: "0.5" },
      { seq: 5, name: "Project Material Arrangement & Kitting", actionBy: "Store Officer / Logistics Support", steps: "Arrange issued materials per project using:\nBill of Quantity (BoQ)\nProject checklist\nBundle or tag materials by project name and code\nConfirm completeness of project materials\nNotify Factory Operations or Logistics that materials are ready", documents: "Bill of Quantity (BoQ)\nProject Checklist\nProject Tag / Label", decisionMaker: null, criteria: null, stakeholders: "Factory Operations\nLogistics\nQuality Control", duration: "0.5" },
    ],
  },
  {
    code: "PROC",
    name: "Procurement",
    category: "Procurement",
    summary: "Stock need through requisition, vendor selection and LPO to receipt and payment.",
    appRoute: "/suppliers",
    sourceSheet: "PROCUREMENT PROCESS MAP updated",
    stages: [
      { seq: 1, name: "Stock Status & Need Identification", actionBy: "Store Officer (SO)", steps: "Review live stock balance to identify out-of-stock, low stock, or minimum restock threshold breach and notify Procurement.", documents: "Live Stock Balance (Zoho Sheet)", decisionMaker: "Store Officer", criteria: "Material out of stock or below minimum level\nNo pending import/order", stakeholders: "Store, Procurement", duration: "0.25 day" },
      { seq: 2, name: "Needs Confirmation", actionBy: "Store Officer \u2192 CPO", steps: "Confirm necessity of materials with User Department and escalate to Procurement leadership.", documents: "Email + Stock Report", decisionMaker: "CPO", criteria: "Operational necessity confirmed\nNo suitable substitute", stakeholders: "CPO, Ops, Finance", duration: "0.25 day" },
      { seq: 3, name: "Material Requisition", actionBy: "Procurement Officer (PO)", steps: "Prepare and submit Material Requisition Form (MRF) with correct specifications and quantities.", documents: "Material Requisition Form (Zoho Sheet)", decisionMaker: "Procurement Officer", criteria: "Correct specs and quantities\nBudgeted item", stakeholders: "PO, Ops", duration: "0.5 day" },
      { seq: 4, name: "Operational Approval", actionBy: "COO", steps: "Review MRF for production priority and operational impact. Approve or amend.", documents: "Approved MRF", decisionMaker: "COO", criteria: "Production impact validated\nPriority confirmed", stakeholders: "COO, Ops", duration: "0.25 day" },
      { seq: 5, name: "Vendor Pre-Approval", actionBy: "Procurement Committee", steps: "Conduct due diligence to ensure vendors meet TRT supplier requirements.", documents: "Approved Vendor / Material List", decisionMaker: "Procurement Committee", criteria: "Vendor registered\nCapacity & delivery capability\nCompetitive pricing", stakeholders: "Procurement Committee", duration: "0.5 day" },
      { seq: 6, name: "RFQ & Vendor Evaluation", actionBy: "Procurement Officer", steps: "Obtain and evaluate quotations based on price, quality, and delivery capability.", documents: "Vendor Comparison Sheet", decisionMaker: "Procurement Officer", criteria: "Competitive price\nQuality specs met\nDelivery timeline acceptable", stakeholders: "PO, Procurement", duration: "0.5 day" },
      { seq: 7, name: "Vendor Selection & Invoice Request", actionBy: "Procurement Officer", steps: "Select preferred vendor and request proforma invoice.", documents: "Proforma Invoice", decisionMaker: "Procurement Officer", criteria: "Best-value vendor selected\nMaterial availability confirmed", stakeholders: "PO", duration: "0.5 day" },
      { seq: 8, name: "Procurement Approval", actionBy: "CPO", steps: "Review vendor selection and commercial terms for policy compliance.", documents: "Approved Vendor & Invoice", decisionMaker: "CPO", criteria: "Procurement policy compliance\nValue-for-money confirmed", stakeholders: "CPO", duration: "0.25 day" },
      { seq: 9, name: "LPO Authorization", actionBy: "CFO", steps: "Authorize issuance of Local Purchase Order based on approvals and cash position.", documents: "Approved MRF + Invoice", decisionMaker: "CFO", criteria: "Funds availability\nApproved procurement list", stakeholders: "CFO, Finance", duration: "0.25 day" },
      { seq: 10, name: "LPO Issuance", actionBy: "Procurement Officer", steps: "Raise and issue LPO to vendor following authorization.", documents: "Local Purchase Order (LPO)", decisionMaker: "Procurement Officer", criteria: "Approved LPO\nVendor acknowledgement", stakeholders: "PO, Vendor", duration: "0.25 day" },
      { seq: 11, name: "Material Supply & Receipt", actionBy: "Store Officer (SO)", steps: "Receive materials, inspect quantity and quality, and document receipt.", documents: "GRN, Waybill, Delivery Note", decisionMaker: "Store Officer", criteria: "Correct specs\nRight quantity\nMaterials in good condition", stakeholders: "Store, QC", duration: "1 day" },
      { seq: 12, name: "Payment Request Submission", actionBy: "Procurement Officer", steps: "Submit complete payment request package to Finance.", documents: "LPO, GRN, Invoice", decisionMaker: "Procurement Officer", criteria: "Complete documentation\nDelivery confirmed", stakeholders: "Finance", duration: "0.25 day" },
      { seq: 13, name: "Funds Release", actionBy: "CFO / Treasury", steps: "Approve and release funds in line with agreed payment terms.", documents: "Bank Platform, Payment Instruction", decisionMaker: "CFO", criteria: "Funds available\nApproved payment request", stakeholders: "CFO, Treasury", duration: "0.25 day" },
      { seq: 14, name: "Payment Execution & Posting", actionBy: "Finance / Accounts Payable", steps: "Execute supplier payment and post transaction in accounting system.", documents: "ERP / Bank Statement", decisionMaker: "Finance", criteria: "Correct beneficiary\nAccurate accounting entry", stakeholders: "Finance", duration: "0.25 day" },
      { seq: 15, name: "Documentation & Audit Trail", actionBy: "Procurement / Finance", steps: "Archive all procurement and payment documents for audit and reference.", documents: "Shared Drive / DMS", decisionMaker: "Finance", criteria: "Complete audit trail\nDocuments properly indexed", stakeholders: "Audit, Management", duration: "0.25 day" },
    ],
  },
  {
    code: "QC",
    name: "Quality Control",
    category: "Production",
    summary: "Inspect finished project components, correct defects, label, package and clear for dispatch.",
    appRoute: null,
    sourceSheet: "QUALITY CONTROL  PROCESS",
    stages: [
      { seq: 1, name: "Receipt of Finished Project", actionBy: "Quality Control Officer", steps: "Receive completed project components from Factory Installation Team\nConfirm project name, sections/spaces, and completion status\nLog receipt into QC register", documents: "QC Intake Register\nProject Design File", decisionMaker: "Factory Project Manager", criteria: null, stakeholders: "Factory Installation Team\nFactory Project Manager (PM)", duration: "1" },
      { seq: 2, name: "Physical Damage Inspection", actionBy: "Quality Control Officer", steps: "Inspect all components for:\nCracks\nBreakages\nScratches\nWarping or visible damage\nIsolate defective items immediately\nReport issues to Factory PM/Installer for correction", documents: "QC Inspection Checklist\nDefect Report Form", decisionMaker: "Factory Project Manager", criteria: null, stakeholders: "Factory PM\nInstallation Team", duration: "1" },
      { seq: 3, name: "Installation & Design Compliance Check", actionBy: "Quality Control Officer", steps: "Cross-check installed components against approved design drawings\nConfirm:\nCorrect dimensions\nProper alignment\nCorrect fixing and installation method\nValidate installation quality with Factory PM/Installer", documents: "Approved Design Drawings\nInstallation Verification Checklist", decisionMaker: "Factory Project Manager", criteria: null, stakeholders: "Factory PM\nInstaller", duration: "1" },
      { seq: 4, name: "Edging & Finishing Inspection", actionBy: "Quality Control Officer", steps: "Inspect edging for:\nUniformity\nProper adhesion\nClean finishing without gaps or peeling\nFlag and return any substandard edging for rework", documents: "Finishing & Edging Checklist", decisionMaker: "Factory Project Manager", criteria: null, stakeholders: "Factory PM\nInstaller", duration: "1" },
      { seq: 5, name: "Cleaning & Surface Treatment", actionBy: "Quality Control Officer", steps: "Clean surfaces using thinner or approved cleaning agents\nRemove stains, glue marks, dust, and fingerprints\nEnsure surfaces are dry and presentable", documents: "Cleaning Materials Log\nSafety Guidelines for Thinner Use", decisionMaker: "Factory Project Manager", criteria: null, stakeholders: "Factory Operations", duration: "1" },
      { seq: 6, name: "Project Labeling & Identification", actionBy: "Quality Control Officer", steps: "Label each component clearly using gum tags\nIndicate:\nProject name\nSpace/location (e.g., Kitchen, Bedroom 1, Office)\nCross-check labels with design and BoQ", documents: "Gum Tags\nProject Space Labeling Guide", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "Logistics\nFactory PM", duration: "1" },
      { seq: 7, name: "Packaging for Safe Delivery", actionBy: "Quality Control Officer", steps: "Wrap items appropriately using:\nNylon\nCartons\nFoam\nPolystyrene\nApply extra protection to fragile components\nConfirm readiness for transportation", documents: "Packaging Checklist\nPackaging Materials", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "Logistics\nStore", duration: "1" },
      { seq: 8, name: "QC Clearance & Handover", actionBy: "Quality Control Officer", steps: "Sign off project as QC-approved\nNotify Logistics for dispatch\nHandover packaged items formally", documents: "QC Clearance Note\nHandover Confirmation", decisionMaker: "Operations Manager", criteria: null, stakeholders: "Logistics\nFactory PM", duration: "1" },
    ],
  },
  {
    code: "PSUP",
    name: "Project Supervision",
    category: "Projects",
    summary: "Intake and site readiness through installation, snagging, client sign-off and closure.",
    appRoute: "/projects",
    sourceSheet: "PROJECT SUPERVISION",
    stages: [
      { seq: 1, name: "Project Intake & Handover", actionBy: "Operations Team", steps: "Formally hand over the awarded project to the PM team", documents: "Signed Contract, BOQ, Drawings, Client Requirements Summary", decisionMaker: "COO", criteria: "Contract signed\nScope defined\nAgreed payment terms for installation fulfilled", stakeholders: "Operations MGR, CTO, and Finance", duration: "1.0" },
      { seq: 2, name: "Site Readiness Confirmation", actionBy: "Project Manager", steps: "Confirm site conditions before production or installation", documents: "Site Readiness Checklist, Site Photos, Client Confirmation", decisionMaker: "CTO", criteria: "Site accessible Power/water available\nMeasurements confirmed", stakeholders: "Client, PM, Ops", duration: "3.0" },
      { seq: 3, name: "Project Review & Kick-off", actionBy: "Project Manager", steps: "Review scope, timelines, risks, and execution requirements,\nValidate drawings against site and brief", documents: "Project Kick-off Checklist, Risk Register\nApproved Production Drawings", decisionMaker: "CTO", criteria: "Scope clarity Feasibility confirmed Risks identified\nDrawings approved\nNo design conflicts", stakeholders: "PM, Ops, Procurement, Factory\nPM, Design, Production", duration: "0.25" },
      { seq: 4, name: "Material Requirement Planning", actionBy: "Project Manager", steps: "Identify materials needed for execution", documents: "Material Requirement List (MRL), BOQ", decisionMaker: "COO", criteria: "Quantities accurate\nSpecs confirmed", stakeholders: "PM, Procurement, Store", duration: "0.25" },
      { seq: 5, name: "Installation Scheduling", actionBy: "Project Manager", steps: "Schedule installers and site activities", documents: "Project Schedule, Gantt Chart", decisionMaker: "COO", criteria: "Resources available Site ready", stakeholders: "PM, Ops Manager, Installers", duration: "0.25" },
      { seq: 6, name: "Quality Inspection & Rectification (Factory Floor)", actionBy: "QC / Project Manager", steps: "Inspect completed works and correct defects at the factory floor", documents: "QC Checklist, Snag List", decisionMaker: "COO", criteria: "No defects identified\nClient specs met", stakeholders: "QC, PM, Ops", duration: "1.0" },
      { seq: 7, name: "Project Execution (Installation)", actionBy: "Project Manager", steps: "Sort materials to identify loss of goods due to damages in transit or other means\nExecute project activities on site", documents: "Weekly Site Reports template, Checklists\nProduction drawings", decisionMaker: "CTO", criteria: "Scope requirements met\nQuality standards met (Definition of Done)\nWeekly reports are sent", stakeholders: "PM, Installers, QC", duration: "18.0" },
      { seq: 8, name: "Quality Inspection & Rectification", actionBy: "Project Manager and Operations", steps: "Inspect completed works and correct defects on site", documents: "QC Checklist, Snag List", decisionMaker: "COO", criteria: "No major defects Client specs met", stakeholders: "PM, Ops", duration: "1.0" },
      { seq: 9, name: "Client Walk-Through & Sign-off", actionBy: "Project Manager", steps: "Present completed work to client for acceptance", documents: "Client Sign-off Form,\nEmail template", decisionMaker: "Client", criteria: "Client satisfied No outstanding snags\nClient sign-off form is duly executed", stakeholders: "Client, PM, Ops", duration: "1.0" },
      { seq: 10, name: "Project Documentation & Reporting", actionBy: "Project Manager", steps: "Compile project records and lessons learned", documents: "Project Close-out Report", decisionMaker: "COO", criteria: "All documents submitted KPIs reviewed", stakeholders: "PM, Management", duration: "1.0" },
      { seq: 11, name: "Project Closure", actionBy: "Project Manager", steps: "Formally close project and hand over to operations", documents: "Completion Certificate, Final Report", decisionMaker: "COO", criteria: "Deliverables completed Documentation archived", stakeholders: "PM, Ops", duration: "0.25" },
    ],
  },
  {
    code: "PROD",
    name: "Production Planning",
    category: "Production",
    summary: "Brief to work programme, BOQ and schedule, then follow production through to close-out.",
    appRoute: null,
    sourceSheet: "PRODUCTION PLANNING PROCESS",
    stages: [
      { seq: 1, name: "RECEIVE BRIEF AND DEVELOP HIGH LEVEL WORK PROGRAM", actionBy: "Production Planning Lead", steps: "Liaise with Customer care/Design team on scope of work", documents: null, decisionMaker: "Operations Manager", criteria: null, stakeholders: "CS/DT/PPL", duration: "1.0" },
      { seq: 2, name: "RECEIVE DESIGN/CUTLIST", actionBy: "Production Planning Lead", steps: "Liaise with Architect on Cutlist", documents: "Final Design\nFinal Cutlist", decisionMaker: "CDO", criteria: null, stakeholders: "DT/PPL", duration: "2.0" },
      { seq: 3, name: "DEVELOP BOQ/BUDGET", actionBy: "Production Planning Lead", steps: "Develop BOQ (Material & Labour Schedule)\nCost Tracker", documents: "BOQ & Cost Tracker on ZohoSheet", decisionMaker: "CPO", criteria: null, stakeholders: "PPL", duration: "2.0" },
      { seq: 4, name: "DEVELOP WORK SCHEDULE", actionBy: "Production Planning Lead", steps: "Come up with Detailed Programme of Work\nIssue log\nChange Request Log", documents: "Programme of Work\nIssue log on Zohosheet", decisionMaker: "Operations Manager", criteria: null, stakeholders: "PPL/PA/OPs MGR", duration: "2.0" },
      { seq: 5, name: "FOLLOW-UP PRODUCTION", actionBy: "Production Planning Lead", steps: "Ensure all units are meeting timeline\nGet Factory Optimised Sheet", documents: null, decisionMaker: "CPO", criteria: null, stakeholders: "PPL/CM/CPO", duration: "3 TO 4" },
      { seq: 6, name: "FOLLOW-UP PROCUREMENT", actionBy: "Production Planning Lead", steps: "Check that materials for project are available\nLiaise with Store & Procurement to get other materials", documents: "Live Stock Balance Zoho Sheet", decisionMaker: "Procurement Manager", criteria: null, stakeholders: "PPL/PO/SO", duration: "3 TO 4" },
      { seq: 7, name: "FOLLOW-UP LOGISTICS", actionBy: "Production Planning Lead", steps: "Liaise with Logistics to schedule delivery", documents: "Delivery checklist, etc", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "PPL/LO", duration: "5.0" },
      { seq: 8, name: "FOLLOW-UP INSTALLATION", actionBy: "Production Planning Lead", steps: "Liaise with PMs on site to promptly resolve issues", documents: "Weekly progress update", decisionMaker: "CTO", criteria: null, stakeholders: "PPL/PS/CTO", duration: "6 TO 8" },
      { seq: 9, name: "PROJECT CLOSE-OUT", actionBy: "Production Planning Lead", steps: null, documents: "Project closure report\nIssue log\nCost tracker doc", decisionMaker: "COO", criteria: null, stakeholders: "PPL/OPs MGR/COO", duration: "9.0" },
    ],
  },
  {
    code: "FACT",
    name: "Factory File & Project",
    category: "Production",
    summary: "Receive and distribute the project file, authorise production and run it through the sections.",
    appRoute: null,
    sourceSheet: "FACTORY FILE AND PROJECT PROCES",
    stages: [
      { seq: 1, name: "Project File Receipt & Distribution", actionBy: "Factory Admin", steps: "Receive project file from Head Office\nRecord project details in computer (project name, location, delivery date)\nSend soft/hard copy to CPO and Operations\nPrepare project sticker and paste in CPO\u2019s office\nDistribute extra design copies to Logistics, Factory PMs, Upholstery, Hardwood", documents: "Project File Register (Excel / ERP)\nProject Sticker Template\nDesign Drawings", decisionMaker: null, criteria: null, stakeholders: "OPS Department\nCPO\nFactory Operations\nLogistics Mgr\nUpholstery Department\nHardwood Department", duration: "0.5" },
      { seq: 2, name: "Project Review & Production Authorization", actionBy: "Chief Production Officer (CPO)", steps: "Review project file with Operations and Heads of Sections\nClarify scope, timelines, and production priorities\nIssue production guidelines\nApprove commencement of production", documents: "Project Review Checklist\nApproved Design File", decisionMaker: null, criteria: null, stakeholders: "Factory Operations\nHeads of Sections\nCompliance Manager", duration: "1.0" },
      { seq: 3, name: "Production Planning & Material Optimization", actionBy: "Factory Operations", steps: "Optimize palette card to generate cut list\nLiaise with Design / Operations for clarifications\nReview cut list with Quality Control\nGenerate Bill of Quantity (BoQ) for board materials\nRequest materials from Inventory\nHand over cut list to Compliance Manager\nMonitor section progress and report to CPO", documents: "Optimized Cut List\nMaterial BoQ Template\nMaterial Request Form", decisionMaker: null, criteria: null, stakeholders: "Quality Control\nDesign Team\nInventory\nCompliance Manager\nCPO", duration: "1 TO 2" },
      { seq: 4, name: "Cutting Process", actionBy: "Cutting Machine / Compliance Manager", steps: "Sign out required board materials from Inventory\nAssign jobs to cutting machine operators\nCut boards according to optimized sheet (size & colour)\nTransfer cut boards to Edge Banding", documents: "Cut List\nMaterial Issue Voucher\nMachine Job Card", decisionMaker: null, criteria: null, stakeholders: "Inventory\nCutting Operators\nEdge Banding Section", duration: "1 TO 2" },
      { seq: 5, name: "Edge Banding Process", actionBy: "Edge Banding Section", steps: "Sort matching edge tapes from Store\nApply edge banding\nInspect edges against specifications\nHand over edged boards to Quality Control", documents: "Edge Specification Sheet\nQC Inspection Checklist", decisionMaker: null, criteria: null, stakeholders: "Store\nQuality Control", duration: "1.0" },
      { seq: 6, name: "Drilling & Grooving Process", actionBy: "Drilling Machine Section", steps: "Check availability of bits, dowels, mili-fix\nRequest missing materials from Store\nDrill, groove, or cut boards as specified\nHand over to Quality Control", documents: "Drilling Layout Drawing\nTool Request Form\nQC Checklist", decisionMaker: null, criteria: null, stakeholders: "Store\nQuality Control", duration: "1.0" },
      { seq: 7, name: "Spray / Finishing Process", actionBy: "Spray Section", steps: "Collect required materials from Store\nSand boards\nSpray and/or polish surfaces\nSubmit finished components to Quality Control", documents: "Finishing Specification Sheet\nStore Requisition Form", decisionMaker: null, criteria: null, stakeholders: "Store\nQuality Control", duration: "1 TO 2" },
      { seq: 8, name: "Hardwood & Upholstery Production", actionBy: "Hardwood & Upholstery Sections", steps: "Review project designs jointly\nIdentify material requirements\nSubmit procurement request via CPO\nProduce hardwood skeletons\nUpholstery completes final products\nNotify Head Office Operations upon completion\nHand over to Logistics", documents: "Upholstery Drawings\nMaterial Requisition Form\nCompletion Notification Template", decisionMaker: null, criteria: null, stakeholders: "CPO\nProcurement\nOperations Departments\nLogistics", duration: "3 TO 5" },
      { seq: 9, name: "Glass Fabrication Process", actionBy: "Glass Section", steps: "Take measurements\nPrepare glass cut list\nConfirm material availability with Store\nInform Logistics of profiles, cast iron, screws needed\nFabricate glass components\nSubmit to Quality Control", documents: "Glass Cut List\nMeasurement Sheet\nMaterial Request Form", decisionMaker: null, criteria: null, stakeholders: "Store\nLogistics\nQuality Control", duration: "1 TO 2" },
      { seq: 10, name: "Quality Control, Coupling & Packaging", actionBy: "Quality Control", steps: "Review designs and cut list with Factory Operations\nVerify accuracy of cut and edged materials\nCouple components according to design & measurements\nReport completed items to Compliance Manager & CPO\nCall Factory PMs / Installers for confirmation\nClean, label, and package items\nHand over to Logistics", documents: "QC Inspection Report\nCoupling Checklist\nPackaging Label", decisionMaker: null, criteria: null, stakeholders: "Factory Operations\nCompliance Manager\nCPO\nLogistics\nInstallers", duration: "1 TO 2" },
      { seq: 11, name: "Logistics & Dispatch", actionBy: "Logistics Department", steps: "Receive design file from Factory Admin\nInput project data into system\nGenerate delivery checklist and BoQ\nSend BoQ to Procurement\nConfirm accessories/materials post-production\nPrepare waybill\nLoad materials into trucks\nDispatch to site", documents: "Logistics Register\nDelivery Checklist\nWaybill\nTruck Loading Sheet", decisionMaker: null, criteria: null, stakeholders: "Factory Admin\nProcurement\nSite Team\nDrivers", duration: "1.0" },
    ],
  },
  {
    code: "LOG",
    name: "Logistics & Delivery",
    category: "Operations",
    summary: "Project file to BoQ, procurement follow-up, loading, dispatch and site handover.",
    appRoute: null,
    sourceSheet: "LOGISTICS PROCESS",
    stages: [
      { seq: 1, name: "Project File Receipt", actionBy: "Logistics Officer", steps: "Receive project file from the Admin Department\nReview project scope, delivery location, and timelines", documents: "Project File\nLogistics Intake Register", decisionMaker: "Operations Manager", criteria: null, stakeholders: "LO - Logistics Officer\nProject Admin", duration: "1" },
      { seq: 2, name: "Project Data Entry", actionBy: "Logistics Officer", steps: "Input project data into logistics system (Odoo / Excel)\nCapture delivery address, project code, and expected delivery window", documents: "Odoo ERP (Logistics / Inventory Module)\nProject Tracker", decisionMaker: "Operations Manager", criteria: null, stakeholders: "Operations Team\nProduction Team\nLogistics Team", duration: "1" },
      { seq: 3, name: "Bill of Quantities (BoQ) Generation", actionBy: "Logistics Officer", steps: "Generate logistics BoQ covering:\nMaterials\nAccessories\nPackaging items\nValidate quantities against project design", documents: "Bill of Quantities Template\nDesign File", decisionMaker: "Chief Production Officer (CPO)", criteria: null, stakeholders: "Factory Operations", duration: "1" },
      { seq: 4, name: "BoQ Review & Approval", actionBy: "Chief Production Officer (CPO)", steps: "Review BoQ for accuracy and completeness\nApprove or return for corrections", documents: "Approved BoQ", decisionMaker: "Chief Production Officer (CPO)", criteria: null, stakeholders: "Logistics\nFactory Operations", duration: "1" },
      { seq: 5, name: "Procurement Coordination", actionBy: "Logistics Officer", steps: "Forward approved BoQ to Procurement\nFollow up to ensure materials are sorted and reserved", documents: "Approved BoQ\nProcurement Request", decisionMaker: "Head of Procurement", criteria: null, stakeholders: "Procurement\nStore/Inventory", duration: "2 to 3" },
      { seq: 6, name: "Production Monitoring", actionBy: "Logistics Officer", steps: "Track production status with Factory\nAlign delivery planning with production timelines", documents: "Production Status Updates", decisionMaker: "Chief Production Officer (CPO)", criteria: null, stakeholders: "Factory\nOperations", duration: "4 to 24" },
      { seq: 7, name: "Project Readiness Confirmation", actionBy: "Logistics Officer", steps: "Obtain readiness confirmation from Factory Project Managers\nConfirm items are fully completed and packaged", documents: "Project Readiness Confirmation", decisionMaker: "Senior Project Manager (PM)", criteria: null, stakeholders: "Factory PMs\nQuality Control", duration: "25.0" },
      { seq: 8, name: "Quality Control for Delivery", actionBy: "Quality Control", steps: "Inspect finished items for delivery suitability\nApprove items for dispatch", documents: "QC Delivery Checklist\nInspection Report", decisionMaker: "Head of Quality Control", criteria: null, stakeholders: "Logistics\nFactory", duration: "26.0" },
      { seq: 9, name: "Quantity Reconfirmation", actionBy: "Logistics Officer", steps: "Reconfirm quantities of materials and accessories\nMatch items against BoQ and QC clearance", documents: "Delivery Checklist\nApproved BoQ", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "Quality Control\nStore", duration: "26.0" },
      { seq: 10, name: "Waybill Preparation", actionBy: "Logistics Officer", steps: "Prepare waybill for delivery\nAttach delivery checklist and site details", documents: "Waybill\nDelivery Checklist", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "Site installer\nDriver", duration: "26.0" },
      { seq: 11, name: "Truck Loading", actionBy: "Logistics Officer / Driver", steps: "Load materials into trucks\nEnsure proper handling and securing of items\nConfirm loaded quantities", documents: "Truck Loading Sheet", decisionMaker: "Logistics Manager", criteria: null, stakeholders: "Drivers\nWarehouse / Factory\nLogistics Officer", duration: "26 to 27" },
      { seq: 12, name: "Dispatch to Site", actionBy: "Logistics Officer", steps: "Dispatch truck to the designated site\nTrack delivery progress", documents: "Dispatch Log", decisionMaker: "Operations Manager", criteria: null, stakeholders: "Client\nSite Team", duration: "27 to 28" },
      { seq: 13, name: "Site Handover & Delivery Confirmation", actionBy: "Logistics Officer / Site PM", steps: "Handover delivered materials to Site Project Manager\nObtain delivery acknowledgment", documents: "Delivery Confirmation Note\nSigned Waybill", decisionMaker: "Site Project Supervisor", criteria: null, stakeholders: "Site PM\nClient Representative", duration: "29.0" },
    ],
  },
  {
    code: "CHG",
    name: "Change Request Management",
    category: "Operations",
    summary: "Capture a change on site, assess feasibility and cost, get approval and execute it.",
    appRoute: null,
    sourceSheet: "QUALITY CONTROL  PROCESS_1",
    stages: [
      { seq: 1, name: "Change Identification (Site Level)", actionBy: "Project Supervisor (On-site)", steps: "Identify change request arising from site condition, client request, or installation issue.\nCapture details, measurements, photos, and reason for change.", documents: "Change Request Form (CRF \u2013 Draft)", decisionMaker: null, criteria: null, stakeholders: "Client,\nProject Supervisor", duration: "1" },
      { seq: 2, name: "Change Request Submission", actionBy: "Project Supervisor (Site)", steps: "Submit completed Change Request Form with supporting documents to Operations.", documents: "Change Request Form, Email / ERP Submission\nPictures", decisionMaker: null, criteria: null, stakeholders: "Operations Team\nProject supervisors", duration: "1" },
      { seq: 3, name: "Change Logging & Initial Review", actionBy: "Operations Manager", steps: "Log change request into ERP/change register. Categorize change (design, material, production, installation).", documents: "ERP (Odoo), Change Register", decisionMaker: null, criteria: null, stakeholders: "OPS MGR\nPS", duration: "1" },
      { seq: 4, name: "Technical Review (Design / Factory)", actionBy: "Factory PM / CPO / Design Team", steps: "Review feasibility of change, assess production impact, rework requirements, and time implications.", documents: "Design Files, Factory Feedback Sheet", decisionMaker: null, criteria: null, stakeholders: "Factory, Design, Operations", duration: "1" },
      { seq: 5, name: "Material Availability Review", actionBy: "Store / Inventory", steps: "Check availability of required materials, quantify additional needs, or confirm substitutions.", documents: "Inventory System\nStore Ledger", decisionMaker: null, criteria: null, stakeholders: "Store Procurement, Operationss", duration: "1" },
      { seq: 6, name: "Cost & Timeline Impact Assessment", actionBy: "Operations & Finance", steps: "Prepare cost implication, determine chargeable or non-chargeable status, revise project timeline if required.", documents: "Change Cost Sheet\nBOQ Adjustment", decisionMaker: null, criteria: null, stakeholders: "Accounts Operations", duration: "1" },
      { seq: 7, name: "Approval & Client Confirmation (if the change request is coming the client and will cost the organization", actionBy: "Operations / Management", steps: "Submit change order to client, obtain written approval and payment confirmation (if applicable).", documents: "Approved\nChange Order\nEmail\nConfirmation", decisionMaker: null, criteria: null, stakeholders: "Client\nManagement\nOperations", duration: "1" },
      { seq: 8, name: "Change Execution Authorization", actionBy: "Operations Manager", steps: "Issue formal instruction to Factory or Store to proceed with approved change. Update project status.", documents: "Change Execution Notice ERP Update", decisionMaker: null, criteria: null, stakeholders: "Store\nFactory\nOPS MGR", duration: "1" },
      { seq: 9, name: "Correction / Modification Execution", actionBy: "Factory / Store", steps: "Modify or reproduce affected components or release additional materials as approved.", documents: "Production Records, Material Issue Voucher", decisionMaker: null, criteria: null, stakeholders: "Store\nFactory", duration: "1" },
      { seq: 10, name: "Quality Control Inspection", actionBy: "Quality Control", steps: "Inspect modified items for compliance with approved change and design standards. Approve for delivery/reinstallation.", documents: "QC Checklist\nInspection Report", decisionMaker: null, criteria: null, stakeholders: "QC\nFactory", duration: "1" },
      { seq: 11, name: "Site Reinstallation", actionBy: "Project Supervisor / Installer", steps: "Install modified components on site and verify alignment with approved change.", documents: "Installation Checklist", decisionMaker: null, criteria: null, stakeholders: "Client\nSite Team", duration: "1" },
      { seq: 12, name: "Change Closure & Reporting", actionBy: "OPS MGR/Project Admin", steps: "Close change request in system, update project records, and archive documentation.", documents: "Change Closure Report, ERP", decisionMaker: null, criteria: null, stakeholders: "Operations, Management", duration: null },
    ],
  },
  {
    code: "OPS",
    name: "Operations Workflow",
    category: "Operations",
    summary: "Quotation and architect assignment through to project delivery oversight.",
    appRoute: null,
    sourceSheet: "OPS PROCESS FLOW",
    stages: [
      { seq: 1, name: "QUOTATION & PROJECT ASSIGNMENT", actionBy: "Operations Team", steps: "Receive approved quotation from Accounts Department\nForward quotation to Head of Design for architect assignment\nFollow up to ensure assigned architect contacts client immediately\nTrack architect\u2013client engagement timeline (must not exceed set window)\nCreate project on Odoo ERP:\nClient details\nScope\nTimelines\nAssigned architect\nSend initial client email including:\nArchitect\u2019s contact details\nProject overview and next steps\nAdd project to master project list sheet\nUpdate project list weekly", documents: "Approved Quotation\nOdoo ERP (Project Module)\nProject List Sheet\nClient Email Template", decisionMaker: null, criteria: null, stakeholders: "Accounts Department\nHead of Design and Assigned Architect\nOPS MGR and Project Admin/CS\nClient", duration: "1 TO 21" },
      { seq: 2, name: "PROJECT CONFIRMATION & DESIGN CORRECTIONS", actionBy: "Operations Team", steps: "Receive project design file from Design Department\nForward design to assigned Project Manager (PM) for review\nPM assigned by CTO and David\nCoordinate design confirmation review with PM and Supervisor\nIf site-readiness complaints arise:\nGather issues from Project Supervisor\nDraft and send formal email to client outlining issues\nAfter design approval:\nArchitect implements corrections\nFinal production-ready design is issued", documents: "Design File\nDesign Review Checklist\nSite Readiness Report\nClient Communication Email", decisionMaker: null, criteria: null, stakeholders: "Design Department\nProject Manager\nCTO\nDavid (Project Supervising Team Lead)\nProject Supervisor\nClient", duration: "1 TO 3 Days" },
      { seq: 3, name: "DESIGN OPERATIONS MEETING & PRODUCTION PREPARATION", actionBy: "Operations Team", steps: "Schedule Design Operations Meeting\nReview finalized design with:\nDesign\nOperations\nFactory (if required)\nResolve production or constructability issues\nApprove design for production\nSend design file to Factory for production\nNotify client via email:\nProduction commencement\nEstimated delivery timeline", documents: "Meeting Agenda & Minutes\nApproved Design File\nProduction Approval Record\nClient Update Email", decisionMaker: null, criteria: null, stakeholders: "Design Team\nOPS MGR/OPS Representative\nFactory\nProject Manager\nClient", duration: "1 to 21" },
      { seq: 4, name: "PRODUCTION COMPLETION & PRE-INSTALLATION CONFIRMATION", actionBy: "Operations Team", steps: "Monitor factory production progress\nNear completion:\nSend payment reminder email for remaining 10% balance\nIssue Delivery Note to Project Manager\nProject Manager confirms site readiness 1 week before delivery\nCall client to confirm:\nSite access\nOn-site representative availability", documents: "Production Status Report\nDelivery Note\nPayment Reminder Email\nCall Log", decisionMaker: null, criteria: null, stakeholders: "Factory\nProject Manager\nClient\nAccounts, COO, OPS MGR AND Project Admin", duration: "7 days before delivery" },
      { seq: 5, name: "INSTALLATION SCHEDULING & EXECUTION FOLLOW-UP", actionBy: "Project Admin Officer", steps: "Schedule installation after site readiness confirmation\nAssign and brief installer\nConfirm installation date, scope, and expectations\nMonitor installation progress\nEscalate issues immediately where required", documents: "Installation Schedule\nInstaller Assignment Sheet\nDaily Progress Update", decisionMaker: null, criteria: null, stakeholders: "Installer\nProject Supervisor\nClient, OPS MGR, COO", duration: "Every day upon commencement of installation" },
      { seq: 6, name: "WEEKLY PROJECT MEETINGS & REPORTING", actionBy: "OPS MGR", steps: "Attend weekly project review meetings\nDiscuss:\nProgress\nRisks\nClient concerns\nDelays\nPrepare weekly project status report\nDistribute report to relevant stakeholders", documents: "Weekly Project Report Template\nMeeting Minutes\nProject Tracker", decisionMaker: null, criteria: null, stakeholders: "Based on needs assessment,Management\nDesign\nFactory\nProject Managers, and all concerned OPS Team members", duration: "Every Monday at 11AM" },
    ],
  },
  {
    code: "INV",
    name: "Invoice Generation",
    category: "Finance",
    summary: "Design brief to priced invoice, reviewed by operations.",
    appRoute: null,
    sourceSheet: "INVOICING PROCESS",
    stages: [
      { seq: 1, name: "RECEIVE BRIEF FROM DESIGN DEPARTMENT", actionBy: "Invoicing Ofiicer", steps: "Design team sends brief to Invoicing Officer", documents: "Brief\nWhatsapp/Email", decisionMaker: "Operations Manager", criteria: null, stakeholders: "DT/IO", duration: "1.0" },
      { seq: 2, name: "CHECK ERP (ERP) FOR CLIENT'S DETAILS", actionBy: "Invoicing Ofiicer", steps: "Identify Client's details on ERP Liase with Customer Service Officer for client's onboarding (if they have not been onboarded)", documents: "ERP", decisionMaker: "Operations Manager", criteria: null, stakeholders: "CS/IO", duration: "1.0" },
      { seq: 3, name: "REVIEW CLIENT'S BRIEF FOR CORRECTIONS", actionBy: "Invoicing Ofiicer", steps: "Confirm dimensions with the design team to check for errors. Confirm actual and required products are indicated in the brief.", documents: "Whatsapp/Email/Phonecall", decisionMaker: "Design Team Lead", criteria: null, stakeholders: "DT/IO", duration: "1.0" },
      { seq: 4, name: "BEGIN INVOICING PROCESS", actionBy: "Invoicing Ofiicer", steps: "Reference the quotation list and calculate the prices of each item on the brief.\nReceive confirmation from the MD for the prices of non-niche items.", documents: "ERP\nMicrosoft Excel Quotation Checklist", decisionMaker: "MD", criteria: null, stakeholders: "IO/CEO/OPs MGR/COO", duration: "1 TO 2" },
      { seq: 5, name: "SEND TO OPERATIONS FOR REVIEW", actionBy: "Invoicing Ofiicer", steps: "Send invoice to Operations Manager.", documents: "Whatsapp/Email/ERP", decisionMaker: "Operations Manager", criteria: null, stakeholders: "Ops MGR/IO", duration: "2 TO 3" },
    ],
  },
  {
    code: "FIN",
    name: "Finance OPEX & CAPEX",
    category: "Finance",
    summary: "Plan, approve and execute operating and capital expenditure.",
    appRoute: null,
    sourceSheet: "FINANCE OPEX PAYMENTS PROCESS",
    stages: [
      { seq: 1, name: "Request Submission", actionBy: "Cost Centre Heads / Location Managers", steps: "Individual cost centres and locations submit OPEX or CAPEX payment requests based on approved budgets.", documents: "Payment Request Form (Excel/ERP) Approved Budget / Cost Code Supporting invoices, contracts, or quotations", decisionMaker: "Cost Centre Head", criteria: null, stakeholders: "Cost Centre Heads, Location Managers", duration: "0.5 Day" },
      { seq: 2, name: "Request Collation", actionBy: "HAP", steps: "All payment requests are reviewed for completeness, accuracy, and budget alignment, then consolidated into a master payment schedule.", documents: "Consolidated Payment Schedule (Excel) Checklist for document completeness ERP or Accounting System", decisionMaker: "Head of Accounts Payable (HAP", criteria: null, stakeholders: "HAP", duration: "0.5 Day" },
      { seq: 3, name: "Internal Validation", actionBy: "HAP", steps: "Requests are validated for duplication, correct vendor details, tax compliance, and payment terms before escalation.", documents: "Vendor Master Data Tax documentation Internal control checklist", decisionMaker: "CFO", criteria: null, stakeholders: "Fin Ops/Tax/CM", duration: "0.25" },
      { seq: 4, name: "Approval Review", actionBy: "CFO (Future: Financial Controller)", steps: "Consolidated payment schedule is reviewed against cash flow position, priorities, and financial controls. Adjustments are made if required.", documents: "Consolidated Payment Schedule Cash Flow Forecast Budget vs Actual Report", decisionMaker: "CFO", criteria: null, stakeholders: "CFO / Financial Controller", duration: "0.5" },
      { seq: 5, name: "Approved List Circulation", actionBy: "CFO (Future: Financial Controller)", steps: "Approved and amended payment list is formally signed off and shared with the Accounts Payable team.", documents: "Approved Payment Schedule (signed) Approval email / workflow system", decisionMaker: "CFO", criteria: null, stakeholders: "CFO / Financial Controller/HAP", duration: "0.25" },
      { seq: 6, name: "Funds Release Authorization", actionBy: "CFO / Treasury", steps: "Funds are released into designated expense or operational accounts in line with the approved payment list.", documents: "Bank Transfer Authorization Treasury Instruction Form Online Banking Platform", decisionMaker: "CFO", criteria: null, stakeholders: "CFO, Treasury, Bank", duration: "0.5 Day" },
      { seq: 7, name: "Payment Execution", actionBy: "HAP", steps: "Payments are executed to vendors or internal beneficiaries based on approved instructions.", documents: "Online Banking Platform ERP Payment Module Vendor Bank Details", decisionMaker: "Head of Accounts Payable (HAP)", criteria: null, stakeholders: "HAP/Vendors", duration: "0.5 Day" },
      { seq: 8, name: "Posting & Reconciliation", actionBy: "HAP / Fin Ops", steps: "Payments are posted to the accounting system and reconciled against bank statements and expense accounts.", documents: "ERP / Accounting System Bank Statements Reconciliation Template", decisionMaker: "CFO", criteria: null, stakeholders: "HAP/FIN OPS", duration: "0.25" },
      { seq: 9, name: "Reporting & Audit Trail", actionBy: "Finance Ops", steps: "Payment reports and supporting documents are archived for audit and management reporting.", documents: "Payment Register Document Management System Audit Trail Folder", decisionMaker: "CFO", criteria: null, stakeholders: "Internal Audit, Management", duration: "0.5 day" },
    ],
  },
  {
    code: "CS",
    name: "Client Enquiry & Onboarding",
    category: "Commercial",
    summary: "Onboard a client, engage the design team and keep them informed through installation.",
    appRoute: null,
    sourceSheet: "CUSTOMER SERVICE PROCESS",
    stages: [
      { seq: 1, name: "CLIENT ONBOARDING (Project Details)", actionBy: "Customer Service/CEO", steps: "Engage the client to get the scope of the project. Get the client's Full Name, site address email address, phone number Put all the details into the designated Zoho sheets", documents: "SMS Whatsapp Instagram Email Call Odoo", decisionMaker: "MD", criteria: null, stakeholders: "CS/MD", duration: "1.0" },
      { seq: 2, name: "ENGAGE DESIGN TEAM", actionBy: "Customer Service/Design Team", steps: "reach out to the design team to assign an architect\nEnsure that the site visit/Use of floor plan provided by client is carried out\nFollow up with the receipt of the project brief sent by architect\nCustomer feedback after design is completed", documents: "Call Whatsapp Email Client's floor plan", decisionMaker: "Head of Design / Design Team Lead", criteria: null, stakeholders: "CS/DT", duration: "1.0" },
      { seq: 3, name: "CRM PROCESS", actionBy: "Customer Service", steps: "Follow up with client's brief to ensure that the entire work scope is captured Populate the Odoo CRM with the confirmed details", documents: "ODOO Client's brief document", decisionMaker: "Operations Manager", criteria: null, stakeholders: "CS/IO", duration: "2.0" },
      { seq: 4, name: "CLIENT EXPERCIENCE CHECK-IN (INSTALLATION PHASE)", actionBy: "Customer Service", steps: "Engage the client to understand their experience with the project so far", documents: "Call CSAT Surveys After sales form Project sign-off document Whatsapp Email", decisionMaker: "Customer service", criteria: null, stakeholders: "CS", duration: "1.0" },
    ],
  },
  {
    code: "HRON",
    name: "New Hire Onboarding",
    category: "People",
    summary: "Reception and workstation through documentation, identity and payroll registration.",
    appRoute: null,
    sourceSheet: "HR NEW HIRE ONBOARDING",
    stages: [
      { seq: 1, name: "Employee Reception & Setup", actionBy: "Admin Officer", steps: "Receive new employee on first day\nAssign workstation\nIntroduce employee to staff", documents: "Onboarding Checklist\nWorkstation Allocation Log", decisionMaker: null, criteria: null, stakeholders: "Line Manager, IT/Admin", duration: "1.0" },
      { seq: 2, name: "Employment Documentation Issuance", actionBy: "Admin / HR Officer", steps: "Issue employment letter\nIssue Non-Compete & NDA\nIssue employee information form", documents: "Employment Letter\nNDA / Non-Compete Agreement\nEmployee Information Form", decisionMaker: null, criteria: null, stakeholders: "Employee, HR", duration: "1.0" },
      { seq: 3, name: "Guarantor & Identity Processing", actionBy: "HR/Admin", steps: "Issue guarantor form\nRetrieve completed guarantor form\nProcess ID card and official email", documents: "Guarantor Form\nID Card Template\nEmail Access Request", decisionMaker: null, criteria: null, stakeholders: "Employee, IT/Admin", duration: "5.0" },
      { seq: 4, name: "System & Payroll Registration", actionBy: "HR Officer", steps: "Upload employee data on Odoo\nAdd employee to payroll\nConfirm inclusion before payroll cutoff", documents: "Odoo HR Module\nPayroll Register", decisionMaker: null, criteria: null, stakeholders: "Finance, CAO", duration: "1.0" },
    ],
  },
  {
    code: "HREX",
    name: "Staff Exit",
    category: "People",
    summary: "Resignation through handover, clearance and final settlement.",
    appRoute: null,
    sourceSheet: "HR EXITING STAFF",
    stages: [
      { seq: 1, name: "Resignation & Acknowledgement", actionBy: "Admin Officer", steps: "Receive resignation letter\nValidate notice period:\nConfirmed staff: 1 month\nProbation staff: 2 weeks\nApply salary forfeiture where applicable\nAcknowledge and forward to CAO", documents: "Resignation Letter\nExit Checklist", decisionMaker: null, criteria: null, stakeholders: "CAO, Line Manager", duration: "0.5" },
      { seq: 2, name: "Clearance & Financial Verification", actionBy: "HR / Finance", steps: "Verify staff financial obligations\nCommunicate exit to HOD\nRetrieve company properties", documents: "Clearance Form\nAsset Handover Checklist", decisionMaker: null, criteria: null, stakeholders: "Finance, HOD", duration: "2 TO 3" },
      { seq: 3, name: "Exit Formalities & Communication", actionBy: "HR/Admin", steps: "Conduct exit interview\nSchedule send-off and gift\nRemove staff from payroll and Odoo\nDisable emails and system access\nSend exit communiqu\u00e9 internally", documents: "Exit Interview Form\nPayroll Update Sheet\nIT Access Revocation Form", decisionMaker: null, criteria: null, stakeholders: "IT, All Staff", duration: "3.0" },
      { seq: 4, name: "System & Payroll Registration", actionBy: "HR Officer", steps: "Upload employee data on Odoo\nAdd employee to payroll\nConfirm inclusion before payroll cutoff", documents: "Odoo HR Module\nPayroll Register", decisionMaker: null, criteria: null, stakeholders: "Finance, CAO", duration: "6.0" },
    ],
  },
  {
    code: "BOARD",
    name: "Board Meeting Setup",
    category: "Governance",
    summary: "Notification through technical setup, verification and post-meeting review.",
    appRoute: null,
    sourceSheet: "BOARD MEETING",
    stages: [
      { seq: 1, name: "Board Meeting Notification", actionBy: "Senior Operations Manager", steps: "Receive confirmed Board meeting date, and time", documents: "Board Calendar, Meeting Notice", decisionMaker: "COO", criteria: "Meeting date officially approved", stakeholders: "Board, MD, Operations", duration: "T-7 Days" },
      { seq: 2, name: "Assign Technical Responsibility", actionBy: "Senior Operations Manager", steps: "Assign Operations Officer/Designate responsible for meeting setup and support", documents: "Responsibility Matrix (RACI), Task Assignment", decisionMaker: "Senior Operations Manager", criteria: "Responsible officer assigned", stakeholders: "Operations Team", duration: "T-7 Days" },
      { seq: 3, name: "Create Virtual Meeting", actionBy: "EA to the MD", steps: "Create Zoom meeting and configure security settings", documents: "Zoom Account, Meeting Template", decisionMaker: "Senior Operations Manager", criteria: "Meeting created with correct settings", stakeholders: "Operations", duration: "T-5 Days" },
      { seq: 4, name: "Configure Meeting Settings", actionBy: "EA to the MD", steps: "Enable waiting room, recording, screen sharing, co-host, password protection", documents: "Zoom Settings Checklist", decisionMaker: "Senior Operations Manager", criteria: "All required settings enabled", stakeholders: "Operations", duration: "T-5 Days" },
      { seq: 5, name: "Circulate Meeting Invitation", actionBy: "EA to the MD", steps: "Send meeting invite and Board papers", documents: "Zoho Mail, Calendar Invite, Board Papers", decisionMaker: "Company Secretary", criteria: "Invitations successfully sent", stakeholders: "Board Members", duration: "T-5 Days" },
      { seq: 6, name: "Prepare Equipment", actionBy: "Senior Operations Manager", steps: "Assemble designated laptop, camera, microphone, speakers, charger and backup devices", documents: "Equipment Checklist", decisionMaker: "Senior Operations Manager", criteria: "All equipment available and functional", stakeholders: "Operations", duration: "T-2 Days" },
      { seq: 7, name: "Technical Verification", actionBy: "Senior Operations Manager", steps: "Conduct full technical testing using the designated meeting laptop", documents: "Technical Verification Checklist", decisionMaker: "Senior Operations Manager", criteria: "Audio, video, internet, recording and screen sharing successfully tested", stakeholders: "Operations", duration: "T-1 Day (24 Hours Before Meeting)" },
      { seq: 8, name: "Configuration Freeze", actionBy: "Senior Operations Manager", steps: "Reserve the tested laptop and prevent equipment changes", documents: "Configuration Freeze Checklist", decisionMaker: "Senior Operations Manager", criteria: "Same equipment confirmed for meeting use", stakeholders: "Operations", duration: "Immediately after testing" },
      { seq: 9, name: "Final Readiness Review", actionBy: "Operations Manager", steps: "Review readiness checklist and approve meeting setup", documents: "Readiness Checklist", decisionMaker: "Senior Operations Manager", criteria: "All checklist items completed", stakeholders: "Operations", duration: "T-1 Day" },
      { seq: 10, name: "Pre-Meeting Verification", actionBy: "EA to the MD", steps: "Power on equipment and conduct final checks before participants join", documents: "Pre-Meeting Checklist", decisionMaker: "Senior Operations Manager", criteria: "Equipment operating correctly", stakeholders: "Operations", duration: "1 Hour Before Meeting" },
      { seq: 11, name: "Launch Meeting", actionBy: "EA to the MD", steps: "Open Zoom meeting, admit participants and verify recording", documents: "Zoom Meeting Dashboard", decisionMaker: "Senior Operations Manager", criteria: "Meeting opens successfully", stakeholders: "Board Members", duration: "30 Minutes Before Meeting" },
      { seq: 12, name: "Technical Support During Meeting", actionBy: "Senior Operations Manager", steps: "Monitor meeting, assist participants and resolve technical issues", documents: "Incident Log", decisionMaker: "Senior Operations Manager", criteria: "Issues resolved promptly without disrupting meeting", stakeholders: "Board Members", duration: "Throughout Meeting" },
      { seq: 13, name: "Meeting Close-Out", actionBy: "EA to the MD", steps: "Stop recording, save attendance, archive files and recording", documents: "Attendance Report, Recording Archive", decisionMaker: "Senior Operations Manager", criteria: "Recording successfully saved", stakeholders: "Company Secretary, Operations", duration: "Immediately After Meeting" },
      { seq: 14, name: "Post-Meeting Review", actionBy: "Senior Operations Manager", steps: "Review technical performance and document lessons learned", documents: "Incident Report, Lessons Learned Register", decisionMaker: "COO", criteria: "Improvement actions identified", stakeholders: "Operations, Executive Management", duration: "Within 1 Working Day" },
      { seq: 15, name: "Continuous Improvement", actionBy: "Senior Operations Manager", steps: "Update SOP and checklist where required", documents: "SOP, Revision Log", decisionMaker: "COO", criteria: "Approved process improvements implemented", stakeholders: "Operations", duration: "As Required" },
    ],
  },
];
